// library/packages/vue/src/greet.vue
<template>
  <div>
    <input
      placeholder="Your name"
      :value="name"
      @change="async (event) => (name = event.target.value)"
    />
    <div>Hello, {{ name }}!</div>
    <div>3</div>
  </div>
</template>

<script setup lang="ts">
import { ref } from "vue";

const name = ref("");
</script>

// library/packages/react/src/greet.tsx
"use client";
import * as React from "react";
import { useState } from "react";

function Greet(props: any) {
  const [name, setName] = useState(() => "");

  return (
    <div>
      <input
        placeholder="Your name"
        value={name}
        onChange={(event) => setName(event.target.value)}
      />
      <div>Hello, {name}!</div>
      <div>3</div>
    </div>
  );
}

export default Greet;
